name: Documentation Tests

on:
  push:
    branches: [main, master]
    paths:
      - "docs/**"
      - "python/**"
      - "src/**"
      - "pyproject.toml"
      - ".github/workflows/docs.yml"
  pull_request:
    branches: [main, master]
    paths:
      - "docs/**"
      - "python/**"
      - "src/**"
      - "pyproject.toml"
      - ".github/workflows/docs.yml"

jobs:
  test-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup dependencies
        uses: ./.github/actions/setup-dependencies
        with:
          python-version: "3.11"
          os: ubuntu-latest

      - name: Set up Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install dependencies
        run: |
          source .venv/bin/activate
          uv pip install -e ".[all]"

      - name: Build evlib
        run: |
          source .venv/bin/activate
          maturin develop --release --features python

      - name: Test documentation examples
        run: |
          source .venv/bin/activate
          pytest --markdown-docs README.md docs/ -v --tb=short --maxfail=10
