name: Documentation Validation and Pages

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libhdf5-dev pkg-config

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install uv
        uv venv
        echo "VIRTUAL_ENV=$PWD/.venv" >> $GITHUB_ENV
        echo "$PWD/.venv/bin" >> $GITHUB_PATH
        source .venv/bin/activate
        uv pip install maturin

    - name: Build and install evlib
      run: |
        source .venv/bin/activate
        maturin develop --release
        # Install with all dependencies needed for documentation tests
        uv pip install -e ".[all]"
        # Verify installation
        python -c "import evlib; print('evlib imported successfully')"

    - name: Test documentation examples
      run: |
        source .venv/bin/activate
        pytest --markdown-docs README.md docs/ -v --tb=short --maxfail=10

    - name: Generate documentation report
      run: |
        echo "Documentation validation complete"
        echo "Total markdown files: $(find docs/ -name '*.md' | wc -l)"
        echo "Python code blocks tested: $(find docs/ README.md -name '*.md' -exec grep -l '```python' {} \; | wc -l)"

    - name: Create documentation summary
      if: github.ref == 'refs/heads/master'
      run: |
        mkdir -p site
        cat > site/index.html << 'EOF'
        <!DOCTYPE html>
        <html>
        <head>
            <title>evlib Documentation</title>
            <meta http-equiv="refresh" content="0; url=https://github.com/tallamjr/evlib/blob/master/README.md">
        </head>
        <body>
            <p>Redirecting to <a href="https://github.com/tallamjr/evlib/blob/master/README.md">evlib documentation</a>...</p>
        </body>
        </html>
        EOF

    - name: Setup Pages
      if: github.ref == 'refs/heads/master'
      uses: actions/configure-pages@v4

    - name: Upload artifact
      if: github.ref == 'refs/heads/master'
      uses: actions/upload-pages-artifact@v3
      with:
        path: site

  deploy:
    if: github.ref == 'refs/heads/master'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
