name: Tag Version

on:
  workflow_run:
    workflows: ["Rust"]
    types: [completed]
    branches: [main, master]

permissions:
  contents: write

jobs:
  create-tag:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Check version change and create tag
        run: |
          git fetch origin ${{ github.event.workflow_run.head_branch }}
          git checkout ${{ github.event.workflow_run.head_sha }}

          if git diff --name-only HEAD^ HEAD | grep -q "Cargo.toml"; then
            if grep -q '^\+version[[:space:]]*=' <(git diff HEAD^ HEAD -- Cargo.toml); then
              VERSION=$(grep '^version[[:space:]]*=' Cargo.toml | head -1 | sed 's/.*"\([^"]*\)".*/\1/')
              echo "Found new version: $VERSION"

              if ! git ls-remote --tags origin | grep -q "refs/tags/v$VERSION"; then
                git config --local user.email "actions@github.com"
                git config --local user.name "GitHub Actions"
                git tag -a "v$VERSION" -m "Release version $VERSION"
                git push origin "v$VERSION"
                echo "Successfully created tag v$VERSION"
              else
                echo "Tag v$VERSION already exists"
              fi
            else
              echo "No version change detected"
            fi
          else
            echo "Cargo.toml not changed"
          fi
